### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by gloorgon** [open-language/en-wordnet#2]
query.forEach((lemma) => {
              ^
TypeError: query.forEach is not a function
    at Database.indexLemmaSearch (/rbd/pnpm-volume/a6869292-193e-4c94-974d-03b60fa0ca68/node_modules/.registry.npmjs.org/en-dictionary/1.2.4/node_modules/en-dictionary/dist/database/index.js:67:15)
    at Dictionary.searchFor (/rbd/pnpm-volume/a6869292-193e-4c94-974d-03b60fa0ca68/node_modules/.registry.npmjs.org/en-dictionary/1.2.4/node_modules/en-dictionary/dist/dictionary/index.js:27:32)
at Object.<anonymous> (/app/start.js:20:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)

**Comment by sudhanshuraheja** [comment]
@gloorgon will look it up this weekend, looks like a bug.

**Comment by makc** [comment]
also tf is this:
https://github.com/open-language/wordnets/blob/master/dist/index.js#L4
https://github.com/open-language/en-wordnet/blob/master/dist/index.js#L3
